# Site settings
title: "An Kaito's Resume"
description: "A resume for GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "An Kaito"
resume_title:                   "Freelancer"
resume_contact_email:           "kaito.an2000@gmail.com"
resume_contact_telephone:       "84 091"
resume_contact_address:         "Saigon, Vietnam"
resume_header_contact_info: "Tran Nao, Saigon, Vietnam | 84 091 | kaito.an2000@gmail.com"
resume_header_intro: "<p>Do what I love, love what I do. Make your production system run faster, better and cheaper!!! With 24/7/265 Online support, contact me if you need a person who keep your zoo!!!</p>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kaitoan2000"
  #resume_twitter_url:           "http://"
  #resume_dribbble_url:          "https://"
  resume_facebook_url:          "https://www.facebook.com/kaito.an2000"
  #resume_linkedin_url:          "https://"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://chuyencuasys.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
